### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by zetheroo** [Jonny007-MKD/password-dialog-title#1]
If I try to manually install the install.rdf Thunderbird says it cannot be installed.

**Comment by Jonny007-MKD** [comment]
Sorry, Github didn't think I should watch this repo even though it is mine, so I didn't see you issue. Please have a look at the [releases](https://github.com/Jonny007-MKD/password-dialog-title/releases)

**Comment by zetheroo** [comment]
Thanks alot. I have the plugin installed in TB, and restarted TB, but no dice. 
I have Keepassxc opened and Browser Integration enabled (for all Browsers).

**Comment by Jonny007-MKD** [comment]
This addon modifies the title of the password dialog so that you can use AutoType. When Thunderbird asks for your mail account's password, is the mail address included in the title of the dialog?

**Comment by zetheroo** [comment]
Ok, thanks. I figured it out. I had to set the Global Auto-Type shortcut in Keepassxc and then had to change the AutoType sequence for the TB KeePass entries from

`{USERNAME}{TAB}{PASSWORD}{ENTER}`
to
`{PASSWORD}{ENTER}`

Now it works. (Note: I had asterisks in one password and it didn't work ... would never authenticate using AutoType ... so I had to set a new password without asterisks and it worked.)

**Comment by radasbona** [comment]
And it works very well. Thanks.

**Comment by zetheroo** [comment]
I don't know what's going on again ... trying to install the latest release and am getting this: could not be installed because it is not compatible with Thunderbird 60.6.1

**Comment by Jonny007-MKD** [comment]
Indeed that's the only change from the previous version, because addons.thunderbird.net didn't want to accept my version as it was. My definition is like this: `minVersion: 60.*, maxVersion: *` so as I understand it this should work... But it doesn't work with my 60.6.1, so we're having the same issue :)

**Comment by zetheroo** [comment]
By the way, here is a little setup How-To I put together ... https://techtalkblog.ch/keepassxc-with-thunderbird-and-autotype-in-ubuntu-18-04/

**Comment by sergeevabc** [comment]
Could you be so kind to make it compatible with Thunderbird 68.*?

**Comment by Jonny007-MKD** [comment]
I created #3 for this.
