### ISSUE TITLE
Support Thunderbird 68

### ISSUE THREAD

**Issue by Jonny007-MKD** [Jonny007-MKD/password-dialog-title#3]
To support Thunderbird 68 the addon has to be converted to MailExtension.

https://developer.thunderbird.net/add-ons/tb68

**Comment by Jonny007-MKD** [comment]
Converting will only help for some months until XUL overlay support gets removed completely.
Afaik there is no way to modify the password dialog with a WebExtension.

**Comment by Jonny007-MKD** [comment]
I created a issue for Thunderbird: https://bugzilla.mozilla.org/show_bug.cgi?id=1594178
It would be the easiest if they implement it directly.

**Comment by sergeevabc** [comment]
It seems there is a slight progress over there on Bugzilla. Good.

**Comment by Jonny007-MKD** [comment]
My patch is going to be included in Thunderbird 74 :)
https://bugzilla.mozilla.org/show_bug.cgi?id=1594178

Also there is a new addon that I haven't tried, yet: https://github.com/kkapsner/keepassxc-mail
